import json
import os

tasks = []
task_id = 1

def add_task(desc, keywords):
    global task_id
    tasks.append({"id": task_id, "task": desc, "expected_keywords": keywords})
    task_id += 1

# --- ALGORITHMIC TASKS (20) ---
add_task("Implement a debounce function in JS. What is the fundamental built-in function used?", ["setTimeout"])
add_task("What data structure is optimal for an LRU Cache to achieve O(1) operations?", ["hash map", "doubly linked list"])
add_task("Flatten a deeply nested array in JS. Name the built-in method that solves this in modern JS.", ["flat"])
add_task("Deep clone a nested object in JS without lodash, avoiding circular reference crashes on modern browsers. Name the modern API.", ["structuredClone"])
add_task("Write a function to detect if a string is a palindrome ignoring punctuation. Which Regex class removes punctuation?", ["\\w", "punctuation"])
add_task("Merge two sorted arrays efficiently. What is the time complexity?", ["O(n+m)", "O(n + m)"])
add_task("Find the first non-repeating character in a string. How many passes over the string are ideal?", ["two", "2"])
add_task("Implement binary search. What is the condition for the while loop?", ["left <= right", "low <= high"])
add_task("Traverse a tree level-by-level. What data structure is required?", ["queue"])
add_task("Find the shortest path in an unweighted graph. Which algorithm is best?", ["BFS", "Breadth First Search"])
add_task("What is the time complexity of QuickSort in the worst case?", ["O(n^2)", "O(n squared)"])
add_task("Which algorithmic paradigm is Dijkstra's algorithm based on?", ["Greedy"])
add_task("How do you prevent integer overflow when calculating the mid-point in binary search? Write the expression.", ["low + (high - low) / 2", "left + (right - left) / 2"])
add_task("What algorithmic technique solves the Fibonacci sequence in O(n) time and O(1) space?", ["dynamic programming", "bottom-up", "iteration"])
add_task("Detect a cycle in a linked list. Name the popular algorithm used.", ["Floyd", "Tortoise", "Hare"])
add_task("Find the Kth largest element in an array efficiently. What data structure is favored?", ["Min-Heap", "Priority Queue"])
add_task("What is the space complexity of a recursive depth-first search on a balanced binary tree?", ["O(h)", "O(log n)"])
add_task("In a Trie, what typically represents the end of a valid word?", ["boolean flag", "isEnd"])
add_task("Reverse a singly linked list. How many pointers do you need at minimum?", ["three", "3"])
add_task("Generate all permutations of a string. Which approach is standard?", ["Backtracking", "recursion"])

# --- LOGIC TASKS (30) ---
add_task("A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost? Answer in cents.", ["5", "five"])
add_task("If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?", ["5", "five"])
add_task("In a lake, there is a patch of lily pads. Every day, the patch doubles in size. If it takes 48 days to cover the entire lake, how long does it take to cover half?", ["47"])
add_task("Some months have 31 days and some have 30 days. How many have 28 days?", ["12", "twelve", "all"])
add_task("You are running a race and pass the person in second place. What place are you in now?", ["Second", "2nd"])
add_task("A farmer has 17 sheep. All but 9 die. How many are left?", ["9", "nine"])
add_task("Divide 30 by 1/2 and add 10. What is the result?", ["70", "seventy"])
add_task("How many times can you subtract 10 from 100?", ["once", "1"])
add_task("If you have a bowl with six apples and you take away four, how many do you have?", ["4", "four"])
add_task("A doctor gives you three pills and tells you to take one every half hour. How long will they last?", ["one hour", "1 hour"])
add_task("How many sides does a circle have?", ["2", "two", "inside and outside"])
add_task("If a blue house is made out of blue bricks, what is a greenhouse made of?", ["glass"])
add_task("Two fathers and two sons go fishing. They each catch one fish, bringing home 3. How?", ["grandfather", "three generations"])
add_task("What comes once in a minute, twice in a moment, but never in a thousand years?", ["m", "the letter m"])
add_task("I have branches, but no fruit, trunk or leaves. What am I?", ["bank"])
add_task("The more of this there is, the less you see. What is it?", ["darkness", "fog"])
add_task("What has many keys but can't open a single lock?", ["piano", "keyboard"])
add_task("What can you catch, but not throw?", ["cold"])
add_task("Forward I am heavy, backward I am not. What am I?", ["Ton"])
add_task("What goes up but never comes down?", ["Age"])
add_task("I am an odd number. Take away a letter and I become even. What number am I?", ["Seven"])
add_task("If you multiply all the numbers on a telephone's dial pad, what is the answer?", ["0", "zero"])
add_task("What invention lets you look right through a wall?", ["Window"])
add_task("What has an eye but cannot see?", ["Needle", "Storm", "Hurricane"])
add_task("What has hands but cannot clap?", ["Clock"])
add_task("It belongs to you, but other people use it more than you do. What is it?", ["Name"])
add_task("What has to be broken before you can use it?", ["Egg"])
add_task("I am tall when I'm young, and I'm short when I'm old. What am I?", ["Candle", "Pencil"])
add_task("What month of the year has 28 days?", ["All of them", "Every month"])
add_task("What is full of holes but still holds water?", ["Sponge"])

# --- CODING TASKS (40) ---
add_task("Write a regex to match a valid IPv4 address. What is the max valid number for a segment?", ["255"])
add_task("How do you extract the domain name from a URL string in Python using a standard library?", ["urllib.parse"])
add_task("In JS, how do you correctly check if a variable `val` is NaN without false positives?", ["Number.isNaN"])
add_task("What SQL clause filters aggregated data grouped by a GROUP BY clause?", ["HAVING"])
add_task("In Python, what keyword yields a generator?", ["yield"])
add_task("What CSS property and value completely removes an element from the document flow?", ["display: none"])
add_task("In React, what hook optimizes heavy computations from running on every render?", ["useMemo"])
add_task("How do you prevent a form from submitting naturally in JS?", ["preventDefault"])
add_task("What command in Git undoes the last commit but keeps the files staged?", ["git reset --soft HEAD~1"])
add_task("In Bash, how do you redirect stderr to a null device?", ["2>/dev/null"])
add_task("What is the time complexity of inserting into a Python dict on average?", ["O(1)"])
add_task("In TypeScript, what utility type constructs a type with all properties of T set to optional?", ["Partial"])
add_task("How do you clear an array in JS while maintaining its reference?", ["length = 0"])
add_task("In Java, what keyword makes a variable’s value unchangeable?", ["final"])
add_task("What Docker command builds an image from a Dockerfile?", ["docker build"])
add_task("In CSS Flexbox, what property aligns items along the cross axis?", ["align-items"])
add_task("What Node.js module handles file system operations?", ["fs"])
add_task("In Python, what decorator defines a method that operates on the class rather than an instance?", ["@classmethod"])
add_task("How do you strictly compare two values for equality in JS?", ["==="])
add_task("What Git command temporarily shelves changes?", ["stash"])
add_task("In SQL, what join type returns all rows from both tables, with nulls where there is no match?", ["FULL OUTER"])
add_task("What method converts a JSON string into a JS object?", ["JSON.parse"])
add_task("In React, what is the second argument to useEffect called?", ["dependency array"])
add_task("What Python built-in function returns the length of a list?", ["len()", "len"])
add_task("How do you add an element to the beginning of an array in JS?", ["unshift()", "unshift"])
add_task("In C++, what operator dynamically allocates memory?", ["new"])
add_task("What bash command searches for a pattern within files?", ["grep"])
add_task("In HTML, what attribute specifies alternative text for an image?", ["alt"])
add_task("What Python structure is an immutable sequential collection?", ["tuple"])
add_task("How does one expose a port in a Dockerfile?", ["EXPOSE"])
add_task("What JS keyword declares a block-scoped local variable?", ["let", "const"])
add_task("In Git, which command fetches and merges changes from the remote tracking branch?", ["git pull"])
add_task("What CSS property alters the transparency of an element?", ["opacity"])
add_task("In Python, what keyword handles exceptions?", ["except"])
add_task("What JS function repeatedly executes code with a fixed time delay?", ["setInterval"])
add_task("In SQL, which clause sorts the result set?", ["ORDER BY"])
add_task("What React hook accesses context values?", ["useContext"])
add_task("How do you remove the last element from a JS array?", ["pop()", "pop"])
add_task("In Bash, what variable holds the exit status of the previous command?", ["$?"])
add_task("What Python method adds an item to the end of a list?", ["append()", "append"])

# --- SYSTEM DESIGN MICRO-TASKS (10) ---
add_task("What pattern restricts instantiation of a class to one single object?", ["Singleton"])
add_task("In a load balancer, what algorithm distributes requests strictly sequentially?", ["Round Robin"])
add_task("What technique hides original database data by replacing it with usable but fake data?", ["Data Masking", "Obfuscation"])
add_task("Which HTTP status code signifies that a resource was permanently moved?", ["301"])
add_task("What type of database is Redis primarily classified as?", ["Key-Value"])
add_task("In microservices, what pattern manages distributed transactions across multiple services?", ["Saga"])
add_task("What mechanism caches API responses at the edge closer to the user?", ["CDN", "Content Delivery Network"])
add_task("Which architecture separates reading data from writing data?", ["CQRS"])
add_task("What tool orchestrates containerized applications at scale?", ["Kubernetes", "K8s"])
add_task("In messaging, what pattern ensures a message is delivered to zero or more subscribers?", ["Pub/Sub", "Publish/Subscribe"])

os.makedirs("phase30", exist_ok=True)
with open("phase30/tasks.json", "w") as f:
    json.dump(tasks, f, indent=2)

print(f"Generated {len(tasks)} extremely hard tasks.")
